# Generated by Django 4.1.4 on 2022-12-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('image', models.ImageField(upload_to='advertisement/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'db_table': 'advertisement_product',
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
