# Generated by Django 4.1.4 on 2022-12-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_photo_delete_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width',
        ),
    ]
