# Generated by Django 4.1.1 on 2022-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_advertisement_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('gmail', models.CharField(max_length=150, verbose_name='Е-мейл')),
                ('number', models.CharField(max_length=150, verbose_name='Телефон')),
                ('message', models.CharField(max_length=150, verbose_name='Сообщение')),
            ],
        ),
    ]
