# Generated by Django 4.1.4 on 2022-12-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_contacts_created_at_news_email_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sender_name',
            field=models.CharField(default=2, max_length=150, verbose_name='Отправитель товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size_of_product',
            field=models.CharField(default=2, max_length=150, verbose_name='Размер товара '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
