# Generated by Django 4.1.4 on 2022-12-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_per_day', models.CharField(max_length=150, verbose_name='Прибыль за один день')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дат добавление'),
        ),
    ]
