# Generated by Django 4.1.4 on 2022-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_for_admin_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_admin',
            name='report_per_month',
            field=models.CharField(default=2, max_length=150, verbose_name='Прибыль за один месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_admin',
            name='report_per_season',
            field=models.CharField(default=1, max_length=150, verbose_name='Прибыль за один сезон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_admin',
            name='report_per_week',
            field=models.CharField(default=1, max_length=150, verbose_name='Прибыль за одну неделю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_admin',
            name='report_per_year',
            field=models.CharField(default=1, max_length=150, verbose_name='Прибыль за один год'),
            preserve_default=False,
        ),
    ]
