# Generated by Django 4.1.4 on 2022-12-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_for_admin_report_per_month_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='For_admin',
            new_name='ForAdmin',
        ),
    ]
